### ISSUE TITLE
TypeError: BSON is not a constructor

### ISSUE THREAD

**Issue by dcsan** [vkarpov15/dookie#14]
I made some I think unrelated changes to an app I'm working on, and am now getting the errors below on  the production DB - but not locally.

I'm not even invoking dookie code, so confusde about whats actually happening. It seems suddenly at startup dookie is crashing wheb being required... ?

└─ dookie@0.2.0

Node 7.9.0
Ubuntu 14.04.5 LTS
$ yarn --version 
1.3.2

```
@tutorweb.rikai-bots.com 340|tutorw | TypeError: BSON is not a constructor
@tutorweb.rikai-bots.com 340|tutorw |     at Object.<anonymous> (/opt/rikai/web-apps/tutorweb/node_modules/dookie/node_modules/mongodb/lib/bulk/ordered.js:15:12)
@tutorweb.rikai-bots.com 340|tutorw |     at Module._compile (module.js:571:32)
@tutorweb.rikai-bots.com 340|tutorw |     at Object.Module._extensions..js (module.js:580:10)
@tutorweb.rikai-bots.com 340|tutorw |     at Module.load (module.js:488:32)
@tutorweb.rikai-bots.com 340|tutorw |     at tryModuleLoad (module.js:447:12)
@tutorweb.rikai-bots.com 340|tutorw |     at Function.Module._load (module.js:439:3)
@tutorweb.rikai-bots.com 340|tutorw |     at Module.require (module.js:498:17)
@tutorweb.rikai-bots.com 340|tutorw |     at require (internal/module.js:20:19)
@tutorweb.rikai-bots.com 340|tutorw |     at Object.<anonymous> (/opt/rikai/web-apps/tutorweb/node_modules/dookie/node_modules/mongodb/lib/apm.js:7:26)
@tutorweb.rikai-bots.com 340|tutorw |     at Module._compile (module.js:571:32)
```

**Comment by dcsan** [comment]
happens at startup

```
$ DEBUG=* node server.js
  express:application set "x-powered-by" to true +0ms
  express:application set "etag" to 'weak' +3ms
  express:application set "etag fn" to [Function: generateETag] +2ms
  express:application set "env" to 'development' +0ms
  express:application set "query parser" to 'extended' +0ms
  express:application set "query parser fn" to [Function: parseExtendedQueryString] +0ms
  express:application set "subdomain offset" to 2 +0ms
  express:application set "trust proxy" to false +1ms
  express:application set "trust proxy fn" to [Function: trustNone] +0ms
  express:application booting in development mode +0ms
  express:application set "view" to [Function: View] +0ms
  express:application set "views" to '/opt/rikai/web-apps/tutorweb/views' +0ms
  express:application set "jsonp callback name" to 'callback' +0ms
/opt/rikai/web-apps/tutorweb/node_modules/dookie/node_modules/mongodb/lib/bulk/ordered.js:15
var bson = new BSON([BSON.Binary, BSON.Code, BSON.DBRef, BSON.Decimal128,
           ^

TypeError: BSON is not a constructor
    at Object.<anonymous> (/opt/rikai/web-apps/tutorweb/node_modules/dookie/node_modules/mongodb/lib/bulk/ordered.js:15:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/rikai/web-apps/tutorweb/node_modules/dookie/node_modules/mongodb/lib/apm.js:7:26)
    at Module._compile (module.js:571:32)
```

confusing thing is that I didnt really change anything server side, or add new modules.

**Comment by dcsan** [comment]
removing dookie from my app and I don't have the startup error anymore ... so a bit concerning.
